[package]
name = "libvelocity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
log = "0.4.21"
pretty_env_logger = "0.5.0"
swift-bridge = "0.1"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
